module.exports = {
    allData:[
        {
            img1:'img/Gallery/Pizza/thumb-FullPizza.jpg'
        },
        {
            img1:'img/Gallery/Pizza/thumb-FullPizza-1.jpg'
        },
        {
            img1:'img/Gallery/Pizza/thumb-Pizza-slice.jpg'
        },
        {
            img1:'img/Gallery/Pizza/thumb-Pizza-slice-1.jpg'
        },
        {
            img1:'img/Gallery/Pizza/thumb-Pizza-slice-2.jpg'
        },
        {
            img1:'img/Gallery/Pizza/thumb-Pizza-slice-3.jpg'
        },
        {
            img1:'img/Gallery/Pizza/thumb-Pizza-slice-4.jpg'
        },
        {
            img1:'img/Gallery/Pizza/thumb-FullPizza-3.jpg'
        },
        {
            img1:'img/Gallery/Shake/thumb-shake.jpg'
        }
        ,
        {
            img1:'img/Gallery/Shake/thumb-shake1.jpg'
        },
        {
            img1:'img/Gallery/Menu/1gourmet-veg.jpg'
        },
        {
            img1:'img/Gallery/Menu/2gourmet-veg2.jpg'
        },
        {
            img1:'img/Gallery/Menu/3gourmet-nonVeg.jpg'
        },
        {
            img1:'img/Gallery/Menu/4chef-special-veg.jpg'
        },
        {
            img1:'img/Gallery/Menu/5chef-special-Nonveg.jpg'
        }
    ],

    pizzaData:[
        {
            img1:'img/Gallery/Pizza/thumb-FullPizza.jpg'
        },
        {
            img1:'img/Gallery/Pizza/thumb-FullPizza-1.jpg'
        },
        {
            img1:'img/Gallery/Pizza/thumb-Pizza-slice.jpg'
        },
        {
            img1:'img/Gallery/Pizza/thumb-Pizza-slice-1.jpg'
        },
        {
            img1:'img/Gallery/Pizza/thumb-Pizza-slice-2.jpg'
        },
        {
            img1:'img/Gallery/Pizza/thumb-Pizza-slice-3.jpg'
        },
        {
            img1:'img/Gallery/Pizza/thumb-Pizza-slice-4.jpg'
        },
        {
            img1:'img/Gallery/Pizza/thumb-FullPizza-3.jpg'
        },
    ],
    shakeData:[
        {
            img1:'img/Gallery/Shake/thumb-shake.jpg'
        },
        {
            img1:'img/Gallery/Shake/thumb-shake1.jpg'
        },
        {
            img1:'img/Gallery/Shake/thumb-shake.jpg'
        },
        {
            img1:'img/Gallery/Shake/thumb-shake1.jpg'
        }
    ],
    menuData:[
        {
            img1:'img/Gallery/Menu/1gourmet-veg.jpg'
        },
        {
            img1:'img/Gallery/Menu/2gourmet-veg2.jpg'
        },
        {
            img1:'img/Gallery/Menu/3gourmet-nonVeg.jpg'
        },
        {
            img1:'img/Gallery/Menu/4chef-special-veg.jpg'
        },
        {
            img1:'img/Gallery/Menu/5chef-special-Nonveg.jpg'
        }
    ],
    bagsData:[
        {
            img:'img/portfolio/3.jpg'
        }
    ],

    shoesData:[
        {
            img:'img/portfolio/3.jpg'
        },
        {
            img:'img/portfolio/3.jpg'
        }
    ],

    watchData:[
        {
            img:'img/portfolio/3.jpg'
        },
        {
            img:'img/portfolio/3.jpg'
        },
        {
            img:'img/portfolio/3.jpg'
        },
        {
            img:'img/portfolio/3.jpg'
        },
        {
            img:'img/portfolio/3.jpg'
        }
    ],
}